FROM --platform=linux/amd64 openjdk:17
WORKDIR /project
COPY ./src/server/java/project/ /project/
COPY ./build/install/cse-110-project-team-31/lib/ /project/
RUN javac -cp "./*" MyServer.java RequestHandler.java ChatGPT.java GPTInterface.java Whisper.java WhisperInterface.java MongoDBProject.java
EXPOSE 8100
ENTRYPOINT ["java", "-cp", "./*", "project/MyServer"]
